import type { LocalizedList } from '../types/index.ts';

/**
 * `en-GB`, not `en`: `Intl.ListFormat('en')` inserts the Oxford comma, and the
 * call for papers was published without one — "catering and local transport",
 * not "catering, and local transport". A locale that changes the punctuation of
 * an archived sentence is not a formatter, it is an edit.
 */
const LIST_LOCALE: Record<string, string> = { en: 'en-GB', fr: 'fr' };

/**
 * "a, b and c" / "a, b et c". The venue page shows the two logistics lists as
 * lists; the call for papers and its PDF downloads need them back as the prose
 * they were published as, so the sentence is composed rather than stored twice.
 *
 * Deliberately free of Paraglide, `$lib` aliases and Svelte: the PDF and text
 * downloads are generated by a plain Node script that imports this file
 * directly. Each caller supplies its own locale and its own sentence frame.
 */
export function joinLogisticsList(list: LocalizedList, locale: 'en' | 'fr'): string {
	const items = list[locale] ?? list.en;
	return new Intl.ListFormat(LIST_LOCALE[locale] ?? 'en-GB', {
		style: 'long',
		type: 'conjunction'
	}).format(items);
}
